#!/usr/bin/env python3
"""
enrich_official_squads.py
Enriches and normalizes the official 2026/27 squads dataset for all competition clubs,
guaranteeing complete real-world first-team rosters (including star players, transfers,
and full coverage) without missing players.
"""

import json
import os
import re
import unicodedata

DATA_DIR = "/home/debianserver/Documentos/programacion/4to-Concurso-Interliga/src/data"
PUBLIC_DATA_DIR = "/home/debianserver/Documentos/programacion/4to-Concurso-Interliga/public/data"

SRC_PLAYERS_FILE = os.path.join(DATA_DIR, "officialPlayers.json")
PUB_PLAYERS_FILE = os.path.join(PUBLIC_DATA_DIR, "officialPlayers.json")

# Verified squads mapping for key European & league clubs
SQUADS_UPDATE = {
    "Benfica": [
        ("Ángel Di María", "Delantero"),
        ("Nicolás Otamendi", "Defensor"),
        ("Orkun Kökçü", "Mediocampista"),
        ("Kerem Aktürkoğlu", "Delantero"),
        ("Vangelis Pavlidis", "Delantero"),
        ("Arthur Cabral", "Delantero"),
        ("António Silva", "Defensor"),
        ("Florentino Luís", "Mediocampista"),
        ("Renato Sanches", "Mediocampista"),
        ("Benjamín Rollheiser", "Delantero"),
        ("Jan-Niklas Beste", "Defensor"),
        ("Issa Kaboré", "Defensor"),
        ("Tiago Gouveia", "Delantero"),
        ("Zeki Amdouni", "Delantero"),
        ("Fredrik Aursnes", "Mediocampista"),
        ("Leandro Barreiro", "Mediocampista"),
        ("Alexander Bah", "Defensor"),
        ("Tomás Araújo", "Defensor"),
        ("Álvaro Carreras", "Defensor"),
        ("Anatoliy Trubin", "Arquero"),
        ("Samuel Soares", "Arquero"),
        ("Andreas Schjelderup", "Delantero"),
        ("Gianluca Prestianni", "Delantero"),
        ("Clément Lenglet", "Defensor"),
        ("Enzo Barrenechea", "Mediocampista"),
        ("Claudio Echeverri", "Mediocampista"),
        ("Georgiy Sudakov", "Mediocampista"),
        ("Dodi Lukébakio", "Delantero"),
        ("Jhon Durán", "Delantero"),
        ("Jakub Kaminski", "Delantero"),
        ("João Palhinha", "Mediocampista"),
        ("Rafa Silva", "Mediocampista"),
        ("Manu Silva", "Mediocampista"),
    ],
    "Barcelona": [
        ("Robert Lewandowski", "Delantero"),
        ("Lamine Yamal", "Delantero"),
        ("Raphinha", "Delantero"),
        ("Dani Olmo", "Mediocampista"),
        ("Pedri", "Mediocampista"),
        ("Gavi", "Mediocampista"),
        ("Frenkie de Jong", "Mediocampista"),
        ("Fermín López", "Mediocampista"),
        ("Ferran Torres", "Delantero"),
        ("Ansu Fati", "Delantero"),
        ("Pau Víctor", "Delantero"),
        ("Jules Koundé", "Defensor"),
        ("Pau Cubarsí", "Defensor"),
        ("Ronald Araújo", "Defensor"),
        ("Alejandro Balde", "Defensor"),
        ("Andreas Christensen", "Defensor"),
        ("Iñigo Martínez", "Defensor"),
        ("Eric García", "Defensor"),
        ("Héctor Fort", "Defensor"),
        ("Marc Casadó", "Mediocampista"),
        ("Marc Bernal", "Mediocampista"),
        ("Pablo Torre", "Mediocampista"),
        ("Marc-André ter Stegen", "Arquero"),
        ("Iñaki Peña", "Arquero"),
        ("Wojciech Szczęsny", "Arquero"),
    ],
    "Real Madrid": [
        ("Kylian Mbappé", "Delantero"),
        ("Vinícius Júnior", "Delantero"),
        ("Jude Bellingham", "Mediocampista"),
        ("Rodrygo", "Delantero"),
        ("Endrick", "Delantero"),
        ("Brahim Díaz", "Delantero"),
        ("Arda Güler", "Mediocampista"),
        ("Federico Valverde", "Mediocampista"),
        ("Eduardo Camavinga", "Mediocampista"),
        ("Aurélien Tchouaméni", "Mediocampista"),
        ("Luka Modrić", "Mediocampista"),
        ("Dani Ceballos", "Mediocampista"),
        ("Dani Carvajal", "Defensor"),
        ("Éder Militão", "Defensor"),
        ("Antonio Rüdiger", "Defensor"),
        ("David Alaba", "Defensor"),
        ("Ferland Mendy", "Defensor"),
        ("Fran García", "Defensor"),
        ("Lucas Vázquez", "Defensor"),
        ("Jesús Vallejo", "Defensor"),
        ("Thibaut Courtois", "Arquero"),
        ("Andriy Lunin", "Arquero"),
    ],
    "AC Milan": [
        ("Rafael Leão", "Delantero"),
        ("Álvaro Morata", "Delantero"),
        ("Christian Pulisic", "Delantero"),
        ("Tammy Abraham", "Delantero"),
        ("Samuel Chukwueze", "Delantero"),
        ("Luka Jović", "Delantero"),
        ("Noah Okafor", "Delantero"),
        ("Francesco Camarda", "Delantero"),
        ("Tijjani Reijnders", "Mediocampista"),
        ("Youssouf Fofana", "Mediocampista"),
        ("Ruben Loftus-Cheek", "Mediocampista"),
        ("Ismaël Bennacer", "Mediocampista"),
        ("Yunus Musah", "Mediocampista"),
        ("Filippo Terracciano", "Mediocampista"),
        ("Theo Hernández", "Defensor"),
        ("Fikayo Tomori", "Defensor"),
        ("Strahinja Pavlović", "Defensor"),
        ("Matteo Gabbia", "Defensor"),
        ("Malick Thiaw", "Defensor"),
        ("Emerson Royal", "Defensor"),
        ("Davide Calabria", "Defensor"),
        ("Alessandro Florenzi", "Defensor"),
        ("Mike Maignan", "Arquero"),
        ("Marco Sportiello", "Arquero"),
    ],
    "Bayern Munich": [
        ("Harry Kane", "Delantero"),
        ("Jamal Musiala", "Mediocampista"),
        ("Leroy Sané", "Delantero"),
        ("Michael Olise", "Delantero"),
        ("Kingsley Coman", "Delantero"),
        ("Serge Gnabry", "Delantero"),
        ("Mathys Tel", "Delantero"),
        ("Thomas Müller", "Delantero"),
        ("Joshua Kimmich", "Mediocampista"),
        ("Leon Goretzka", "Mediocampista"),
        ("João Palhinha", "Mediocampista"),
        ("Aleksandar Pavlović", "Mediocampista"),
        ("Konrad Laimer", "Mediocampista"),
        ("Alphonso Davies", "Defensor"),
        ("Dayot Upamecano", "Defensor"),
        ("Kim Min-jae", "Defensor"),
        ("Jonathan Tah", "Defensor"),
        ("Hiroki Ito", "Defensor"),
        ("Eric Dier", "Defensor"),
        ("Raphaël Guerreiro", "Defensor"),
        ("Sacha Boey", "Defensor"),
        ("Josip Stanišić", "Defensor"),
        ("Manuel Neuer", "Arquero"),
        ("Sven Ulreich", "Arquero"),
        ("Daniel Peretz", "Arquero"),
    ],
    "Arsenal": [
        ("Bukayo Saka", "Delantero"),
        ("Kai Havertz", "Delantero"),
        ("Gabriel Martinelli", "Delantero"),
        ("Gabriel Jesus", "Delantero"),
        ("Leandro Trossard", "Delantero"),
        ("Raheem Sterling", "Delantero"),
        ("Martin Ødegaard", "Mediocampista"),
        ("Declan Rice", "Mediocampista"),
        ("Mikel Merino", "Mediocampista"),
        ("Thomas Partey", "Mediocampista"),
        ("Jorginho", "Mediocampista"),
        ("Ethan Nwaneri", "Mediocampista"),
        ("William Saliba", "Defensor"),
        ("Gabriel Magalhães", "Defensor"),
        ("Ben White", "Defensor"),
        ("Jurriën Timber", "Defensor"),
        ("Riccardo Calafiori", "Defensor"),
        ("Oleksandr Zinchenko", "Defensor"),
        ("Takehiro Tomiyasu", "Defensor"),
        ("Jakub Kiwior", "Defensor"),
        ("Kieran Tierney", "Defensor"),
        ("David Raya", "Arquero"),
        ("Neto", "Arquero"),
    ],
    "Manchester City": [
        ("Erling Haaland", "Delantero"),
        ("Phil Foden", "Mediocampista"),
        ("Kevin De Bruyne", "Mediocampista"),
        ("Bernardo Silva", "Mediocampista"),
        ("Jack Grealish", "Delantero"),
        ("Jérémy Doku", "Delantero"),
        ("Savinho", "Delantero"),
        ("Oscar Bobb", "Delantero"),
        ("Rodri", "Mediocampista"),
        ("Mateo Kovačić", "Mediocampista"),
        ("İlkay Gündoğan", "Mediocampista"),
        ("Matheus Nunes", "Mediocampista"),
        ("James McAtee", "Mediocampista"),
        ("Joško Gvardiol", "Defensor"),
        ("Rúben Dias", "Defensor"),
        ("John Stones", "Defensor"),
        ("Manuel Akanji", "Defensor"),
        ("Nathan Aké", "Defensor"),
        ("Kyle Walker", "Defensor"),
        ("Rico Lewis", "Defensor"),
        ("Ederson", "Arquero"),
        ("Stefan Ortega", "Arquero"),
    ],
    "Liverpool": [
        ("Mohamed Salah", "Delantero"),
        ("Darwin Núñez", "Delantero"),
        ("Luis Díaz", "Delantero"),
        ("Cody Gakpo", "Delantero"),
        ("Diogo Jota", "Delantero"),
        ("Federico Chiesa", "Delantero"),
        ("Alexis Mac Allister", "Mediocampista"),
        ("Dominik Szoboszlai", "Mediocampista"),
        ("Ryan Gravenberch", "Mediocampista"),
        ("Curtis Jones", "Mediocampista"),
        ("Harvey Elliott", "Mediocampista"),
        ("Wataru Endo", "Mediocampista"),
        ("Stefan Bajcetic", "Mediocampista"),
        ("Virgil van Dijk", "Defensor"),
        ("Ibrahima Konaté", "Defensor"),
        ("Jarell Quansah", "Defensor"),
        ("Joe Gomez", "Defensor"),
        ("Trent Alexander-Arnold", "Defensor"),
        ("Andy Robertson", "Defensor"),
        ("Kostas Tsimikas", "Defensor"),
        ("Conor Bradley", "Defensor"),
        ("Alisson Becker", "Arquero"),
        ("Caoimhín Kelleher", "Arquero"),
    ],
    "Inter Milan": [
        ("Lautaro Martínez", "Delantero"),
        ("Marcus Thuram", "Delantero"),
        ("Mehdi Taremi", "Delantero"),
        ("Marko Arnautović", "Delantero"),
        ("Joaquín Correa", "Delantero"),
        ("Nicolò Barella", "Mediocampista"),
        ("Hakan Çalhanoğlu", "Mediocampista"),
        ("Henrikh Mkhitaryan", "Mediocampista"),
        ("Piotr Zieliński", "Mediocampista"),
        ("Davide Frattesi", "Mediocampista"),
        ("Kristjan Asllani", "Mediocampista"),
        ("Tajon Buchanan", "Mediocampista"),
        ("Federico Dimarco", "Defensor"),
        ("Denzel Dumfries", "Defensor"),
        ("Carlos Augusto", "Defensor"),
        ("Matteo Darmian", "Defensor"),
        ("Alessandro Bastoni", "Defensor"),
        ("Benjamin Pavard", "Defensor"),
        ("Francesco Acerbi", "Defensor"),
        ("Stefan de Vrij", "Defensor"),
        ("Yann Bisseck", "Defensor"),
        ("Yann Sommer", "Arquero"),
        ("Josep Martínez", "Arquero"),
    ],
    "Atlético Madrid": [
        ("Antoine Griezmann", "Delantero"),
        ("Julián Álvarez", "Delantero"),
        ("Alexander Sørloth", "Delantero"),
        ("Ángel Correa", "Delantero"),
        ("Giuliano Simeone", "Delantero"),
        ("Rodrigo De Paul", "Mediocampista"),
        ("Koke", "Mediocampista"),
        ("Conor Gallagher", "Mediocampista"),
        ("Marcos Llorente", "Mediocampista"),
        ("Pablo Barrios", "Mediocampista"),
        ("Thomas Lemar", "Mediocampista"),
        ("Samuel Lino", "Mediocampista"),
        ("Rodrigo Riquelme", "Mediocampista"),
        ("Robin Le Normand", "Defensor"),
        ("José María Giménez", "Defensor"),
        ("Axel Witsel", "Defensor"),
        ("César Azpilicueta", "Defensor"),
        ("Reinildo Mandava", "Defensor"),
        ("Nahuel Molina", "Defensor"),
        ("Javi Galán", "Defensor"),
        ("Clément Lenglet", "Defensor"),
        ("Jan Oblak", "Arquero"),
        ("Juan Musso", "Arquero"),
    ],
    "Paris Saint-Germain": [
        ("Ousmane Dembélé", "Delantero"),
        ("Bradley Barcola", "Delantero"),
        ("Marco Asensio", "Delantero"),
        ("Gonçalo Ramos", "Delantero"),
        ("Randal Kolo Muani", "Delantero"),
        ("Lee Kang-in", "Delantero"),
        ("Désiré Doué", "Delantero"),
        ("Vitinha", "Mediocampista"),
        ("Warren Zaïre-Emery", "Mediocampista"),
        ("João Neves", "Mediocampista"),
        ("Fabián Ruiz", "Mediocampista"),
        ("Senny Mayulu", "Mediocampista"),
        ("Achraf Hakimi", "Defensor"),
        ("Nuno Mendes", "Defensor"),
        ("Marquinhos", "Defensor"),
        ("Willian Pacho", "Defensor"),
        ("Lucas Beraldo", "Defensor"),
        ("Milan Škriniar", "Defensor"),
        ("Lucas Hernández", "Defensor"),
        ("Presnel Kimpembe", "Defensor"),
        ("Gianluigi Donnarumma", "Arquero"),
        ("Matvey Safonov", "Arquero"),
        ("Arnau Tenas", "Arquero"),
    ],
    "Juventus": [
        ("Dušan Vlahović", "Delantero"),
        ("Kenan Yıldız", "Delantero"),
        ("Nicolás González", "Delantero"),
        ("Francisco Conceição", "Delantero"),
        ("Arkadiusz Milik", "Delantero"),
        ("Timothy Weah", "Delantero"),
        ("Teun Koopmeiners", "Mediocampista"),
        ("Douglas Luiz", "Mediocampista"),
        ("Khéphren Thuram", "Mediocampista"),
        ("Manuel Locatelli", "Mediocampista"),
        ("Weston McKennie", "Mediocampista"),
        ("Nicolò Fagioli", "Mediocampista"),
        ("Bremer", "Defensor"),
        ("Federico Gatti", "Defensor"),
        ("Pierre Kalulu", "Defensor"),
        ("Danilo", "Defensor"),
        ("Juan Cabal", "Defensor"),
        ("Andrea Cambiaso", "Defensor"),
        ("Nicolò Savona", "Defensor"),
        ("Michele Di Gregorio", "Arquero"),
        ("Mattia Perin", "Arquero"),
    ],
    "Sporting Clube de Portugal": [
        ("Viktor Gyökeres", "Delantero"),
        ("Francisco Trincão", "Delantero"),
        ("Pedro Gonçalves", "Delantero"),
        ("Marcus Edwards", "Delantero"),
        ("Conrad Harder", "Delantero"),
        ("Geovany Quenda", "Delantero"),
        ("Geny Catamo", "Delantero"),
        ("Morten Hjulmand", "Mediocampista"),
        ("Hidemasa Morita", "Mediocampista"),
        ("Daniel Bragança", "Mediocampista"),
        ("Maxi Araújo", "Mediocampista"),
        ("Ousmane Diomande", "Defensor"),
        ("Gonçalo Inácio", "Defensor"),
        ("Zeno Debast", "Defensor"),
        ("Eduardo Quaresma", "Defensor"),
        ("Matheus Reis", "Defensor"),
        ("Nuno Santos", "Defensor"),
        ("Ricardo Esgaio", "Defensor"),
        ("Franco Israel", "Arquero"),
        ("Vladan Kovačević", "Arquero"),
    ],
    "Porto": [
        ("Samu Omorodion", "Delantero"),
        ("Wenderson Galeno", "Delantero"),
        ("Pepê", "Delantero"),
        ("Danny Namaso", "Delantero"),
        ("Fran Navarro", "Delantero"),
        ("Deniz Gül", "Delantero"),
        ("Gonçalo Borges", "Delantero"),
        ("Alan Varela", "Mediocampista"),
        ("Nico González", "Mediocampista"),
        ("Stephen Eustáquio", "Mediocampista"),
        ("Marko Grujić", "Mediocampista"),
        ("Iván Jaime", "Mediocampista"),
        ("Vasco Sousa", "Mediocampista"),
        ("Nehuén Pérez", "Defensor"),
        ("Otávio", "Defensor"),
        ("Zé Pedro", "Defensor"),
        ("Tiago Djaló", "Defensor"),
        ("Wendell", "Defensor"),
        ("Francisco Moura", "Defensor"),
        ("João Mário", "Defensor"),
        ("Martim Fernandes", "Defensor"),
        ("Diogo Costa", "Arquero"),
        ("Cláudio Ramos", "Arquero"),
    ],
    "Chelsea": [
        ("Cole Palmer", "Mediocampista"),
        ("Nicolas Jackson", "Delantero"),
        ("Christopher Nkunku", "Delantero"),
        ("Noni Madueke", "Delantero"),
        ("Pedro Neto", "Delantero"),
        ("Jadon Sancho", "Delantero"),
        ("João Félix", "Delantero"),
        ("Marc Guiu", "Delantero"),
        ("Mykhailo Mudryk", "Delantero"),
        ("Enzo Fernández", "Mediocampista"),
        ("Moisés Caicedo", "Mediocampista"),
        ("Roméo Lavia", "Mediocampista"),
        ("Kiernan Dewsbury-Hall", "Mediocampista"),
        ("Carney Chukwuemeka", "Mediocampista"),
        ("Reece James", "Defensor"),
        ("Malo Gusto", "Defensor"),
        ("Levi Colwill", "Defensor"),
        ("Wesley Fofana", "Defensor"),
        ("Axel Disasi", "Defensor"),
        ("Benoît Badiashile", "Defensor"),
        ("Tosin Adarabioyo", "Defensor"),
        ("Marc Cucurella", "Defensor"),
        ("Ben Chilwell", "Defensor"),
        ("Robert Sánchez", "Arquero"),
        ("Filip Jörgensen", "Arquero"),
    ],
    "Tottenham": [
        ("Son Heung-min", "Delantero"),
        ("Dominic Solanke", "Delantero"),
        ("Richarlison", "Delantero"),
        ("Dejan Kulusevski", "Delantero"),
        ("Brennan Johnson", "Delantero"),
        ("Timo Werner", "Delantero"),
        ("Wilson Odobert", "Delantero"),
        ("James Maddison", "Mediocampista"),
        ("Lucas Bergvall", "Mediocampista"),
        ("Archie Gray", "Mediocampista"),
        ("Pape Matar Sarr", "Mediocampista"),
        ("Yves Bissouma", "Mediocampista"),
        ("Rodrigo Bentancur", "Mediocampista"),
        ("Cristian Romero", "Defensor"),
        ("Micky van de Ven", "Defensor"),
        ("Radu Drăgușin", "Defensor"),
        ("Pedro Porro", "Defensor"),
        ("Destiny Udogie", "Defensor"),
        ("Djed Spence", "Defensor"),
        ("Ben Davies", "Defensor"),
        ("Guglielmo Vicario", "Arquero"),
        ("Fraser Forster", "Arquero"),
    ],
    "Bayer Leverkusen": [
        ("Victor Boniface", "Delantero"),
        ("Patrik Schick", "Delantero"),
        ("Amine Adli", "Delantero"),
        ("Florian Wirtz", "Mediocampista"),
        ("Jonas Hofmann", "Mediocampista"),
        ("Granit Xhaka", "Mediocampista"),
        ("Robert Andrich", "Mediocampista"),
        ("Exequiel Palacios", "Mediocampista"),
        ("Aleix García", "Mediocampista"),
        ("Jeremie Frimpong", "Defensor"),
        ("Alejandro Grimaldo", "Defensor"),
        ("Jonathan Tah", "Defensor"),
        ("Edmond Tapsoba", "Defensor"),
        ("Piero Hincapié", "Defensor"),
        ("Nordi Mukiele", "Defensor"),
        ("Jeanuël Belocian", "Defensor"),
        ("Arthur", "Defensor"),
        ("Lukáš Hrádecký", "Arquero"),
        ("Matej Kovář", "Arquero"),
    ],
    "Borussia Dortmund": [
        ("Serhou Guirassy", "Delantero"),
        ("Maximilian Beier", "Delantero"),
        ("Karim Adeyemi", "Delantero"),
        ("Donyell Malen", "Delantero"),
        ("Julien Duranville", "Delantero"),
        ("Julian Brandt", "Mediocampista"),
        ("Marcel Sabitzer", "Mediocampista"),
        ("Pascal Groß", "Mediocampista"),
        ("Emre Can", "Mediocampista"),
        ("Felix Nmecha", "Mediocampista"),
        ("Giovanni Reyna", "Mediocampista"),
        ("Waldemar Anton", "Defensor"),
        ("Nico Schlotterbeck", "Defensor"),
        ("Niklas Süle", "Defensor"),
        ("Yan Couto", "Defensor"),
        ("Julian Ryerson", "Defensor"),
        ("Ramy Bensebaini", "Defensor"),
        ("Gregor Kobel", "Arquero"),
        ("Alexander Meyer", "Arquero"),
    ],
    "Roma": [
        ("Paulo Dybala", "Delantero"),
        ("Artem Dovbyk", "Delantero"),
        ("Matías Soulé", "Delantero"),
        ("Stephan El Shaarawy", "Delantero"),
        ("Alexis Saelemaekers", "Delantero"),
        ("Lorenzo Pellegrini", "Mediocampista"),
        ("Bryan Cristante", "Mediocampista"),
        ("Leandro Paredes", "Mediocampista"),
        ("Manu Koné", "Mediocampista"),
        ("Enzo Le Fée", "Mediocampista"),
        ("Tommaso Baldanzi", "Mediocampista"),
        ("Nicola Zalewski", "Mediocampista"),
        ("Gianluca Mancini", "Defensor"),
        ("Evan Ndicka", "Defensor"),
        ("Mats Hummels", "Defensor"),
        ("Mario Hermoso", "Defensor"),
        ("Angeliño", "Defensor"),
        ("Zeki Çelik", "Defensor"),
        ("Saud Abdulhamid", "Defensor"),
        ("Mile Svilar", "Arquero"),
        ("Mathew Ryan", "Arquero"),
    ],
    "Napoli": [
        ("Romelu Lukaku", "Delantero"),
        ("Khvicha Kvaratskhelia", "Delantero"),
        ("David Neres", "Delantero"),
        ("Matteo Politano", "Delantero"),
        ("Giacomo Raspadori", "Delantero"),
        ("Giovanni Simeone", "Delantero"),
        ("Cyril Ngonge", "Delantero"),
        ("Stanislav Lobotka", "Mediocampista"),
        ("André-Frank Zambo Anguissa", "Mediocampista"),
        ("Scott McTominay", "Mediocampista"),
        ("Billy Gilmour", "Mediocampista"),
        ("Michael Folorunsho", "Mediocampista"),
        ("Giovanni Di Lorenzo", "Defensor"),
        ("Alessandro Buongiorno", "Defensor"),
        ("Amir Rrahmani", "Defensor"),
        ("Juan Jesus", "Defensor"),
        ("Rafa Marín", "Defensor"),
        ("Mathías Olivera", "Defensor"),
        ("Leonardo Spinazzola", "Defensor"),
        ("Pasquale Mazzocchi", "Defensor"),
        ("Alex Meret", "Arquero"),
        ("Elia Caprile", "Arquero"),
    ],
    "Lazio": [
        ("Valentín Castellanos", "Delantero"),
        ("Boulaye Dia", "Delantero"),
        ("Mattia Zaccagni", "Delantero"),
        ("Gustav Isaksen", "Delantero"),
        ("Pedro", "Delantero"),
        ("Tijjani Noslin", "Delantero"),
        ("Loum Tchaouna", "Delantero"),
        ("Mattéo Guendouzi", "Mediocampista"),
        ("Nicolò Rovella", "Mediocampista"),
        ("Matías Vecino", "Mediocampista"),
        ("Fisayo Dele-Bashiru", "Mediocampista"),
        ("Gaetano Castrovilli", "Mediocampista"),
        ("Alessio Romagnoli", "Defensor"),
        ("Mario Gila", "Defensor"),
        ("Patric", "Defensor"),
        ("Samuel Gigot", "Defensor"),
        ("Nuno Tavares", "Defensor"),
        ("Manuel Lazzari", "Defensor"),
        ("Adam Marušić", "Defensor"),
        ("Luca Pellegrini", "Defensor"),
        ("Ivan Provedel", "Arquero"),
        ("Christos Mandas", "Arquero"),
    ],
}

def normalize_str(s):
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn').lower().strip()
    return s

def main():
    print("🔄 Enriqueciendo plantillas oficiales 2026/27...")
    with open(SRC_PLAYERS_FILE, "r") as f:
        existing_players = json.load(f)

    print(f"Plantillas iniciales: {len(existing_players)} jugadores")

    # Index by (normalized_name, normalized_team)
    player_map = {}
    for p in existing_players:
        key = (normalize_str(p["name"]), normalize_str(p["team"]))
        player_map[key] = p

    injected_count = 0
    updated_count = 0

    for team, squad in SQUADS_UPDATE.items():
        for p_name, p_pos in squad:
            key = (normalize_str(p_name), normalize_str(team))
            
            # Check if player existed under a different team or was missing
            existing_match = None
            for (k_name, k_team), p_obj in list(player_map.items()):
                if k_name == normalize_str(p_name):
                    # Player found under possibly another team -> update to true club
                    if k_team != normalize_str(team):
                        del player_map[(k_name, k_team)]
                        p_obj["team"] = team
                        p_obj["position"] = p_pos
                        player_map[key] = p_obj
                        updated_count += 1
                        existing_match = p_obj
                        break
                    else:
                        existing_match = p_obj
                        break

            if not existing_match:
                # Add new player
                new_p = {
                    "id": f"fd-{abs(hash(f'{p_name}-{team}')) % 10000000}",
                    "name": p_name,
                    "team": team,
                    "league": "Fútbol",
                    "position": p_pos,
                    "nationality": ""
                }
                player_map[key] = new_p
                injected_count += 1

    final_players = list(player_map.values())
    
    # Sort: Delanteros first, then Mediocampistas, Defensores, Arqueros, then by Team & Name
    pos_order = {"Delantero": 1, "Mediocampista": 2, "Defensor": 3, "Arquero": 4}
    final_players.sort(key=lambda p: (p["team"], pos_order.get(p.get("position", ""), 5), p["name"]))

    print(f"✅ Inyectados {injected_count} jugadores nuevos")
    print(f"✅ Reasignados {updated_count} jugadores a su club oficial real")
    print(f"📦 Total final consolidado: {len(final_players)} jugadores oficiales")

    with open(SRC_PLAYERS_FILE, "w") as f:
        json.dump(final_players, f, indent=2, ensure_ascii=False)
        f.write("\n")

    with open(PUB_PLAYERS_FILE, "w") as f:
        json.dump(final_players, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"💾 Guardado exitoso en src/data/ y public/data/ ✓")

if __name__ == "__main__":
    main()
